Models/ErrorViewModel.cs
namespace PdfViewer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FileClass.cs
namespace PdfViewer.Models
{
    public class FileClass
    {
        public int FileId { get; set; } = 0;
        public string Name { get; set; } = "";

        public string Path { get; set; } = "";

        public List<FileClass> Files { get; set; }  = new List<FileClass>(); 

    }
}

Controllers/Files1Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using PdfViewer.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace PdfViewer.Controllers
{
    public class Files1Controller : Controller
    {

        IHostingEnvironment _hostingEnvironment ;

        public Files1Controller(IHostingEnvironment hostingEnvironment)
        {
            this._hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index(string fileName="",bool isDelete = false)
        {
            FileClass fileObj = new FileClass();
            fileObj.Name = fileName;
           
            if (isDelete)
            {
                string filePath = $"{_hostingEnvironment.WebRootPath}\\files\\{fileObj.Name}";

                
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
            }

            //pdf will upload in this folder
            string path = $"{_hostingEnvironment.WebRootPath}\\files\\";

            int nId = 1;

            foreach(string pdfPath in Directory.EnumerateFiles(path, "*.pdf"))
            {
                fileObj.Files.Add(new FileClass()
                {
                    FileId = nId++,
                    Name = Path.GetFileName(pdfPath),
                    Path = pdfPath

                });
            }

            return View(fileObj);
        }


        [HttpPost]
        public IActionResult Index(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment )
        {         
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
            }
            return Index();
        }
        
        public IActionResult PDFViewerNewTab(string fileName)
        {
            string path = $"{_hostingEnvironment.WebRootPath}\\files\\{fileName}";
           
            return File(System.IO.File.ReadAllBytes(path),"application/pdf");
        }



    }

}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PdfViewer.Models;
using System.Diagnostics;

namespace PdfViewer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Files1/Index.cshtml
@model FileClass
@{
    Layout = null;
}

<form asp-controller="Files1" asp-action="Index" method="post" enctype="multipart/form-data">
    
    <input type="file" name="file" />
    <hr />
    <button type="submit">Upload</button>


</form>

@if(Model != null)
{
    <hr />
    <table class="table table-bordered table-striped" cellpadding="0" cellspacing="0" border="1">
        <thead>
            <tr>
                <th>SL    </th>
                <th>PDF Name    </th>
                <th>Display Type    </th>
                <th>Display Type    </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody >
             @foreach(FileClass file in Model.Files)
            {
                <tr>
                    <td>@file.FileId</td>
                    <td>@file.Name</td>
                    <td>
                        <a href="../Files1/index?fileName=@file.Name" style="margin-right:10px;">Page courante</a>
                        <a href="../Files1/PDFViewerNewTab?fileName=@file.Name" target="_blank" style="margin-right:10px;">Nouvel Onglet</a>
                    </td>
                    <td>
                        <a href="../Files1/index?fileName=@file.Name&isDelete=true" style="margin-right:10px;">supprimer</a>
                       
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

             <embed  id="embPDF" src="/files/@Model.Name" style="width:100%"; height="1200px"/>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PdfViewer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PdfViewer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PdfViewer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PdfViewer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>